# Generated by Django 5.0 on 2023-12-10 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rcomments",
                to="home.comment",
            ),
        ),
    ]
